version: '3.1'
services:
  postgres:
    image: postgres
    container_name: module_3
    restart: on-failure
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./init-scripts:/docker-entrypoint-initdb.d/
